import React from 'react';
import Relic from './relic';

function RelicList() {
    const relicList = [
        { name: 'Ascetics Vow', index: '4001' },
        { name: 'Dwarf Kings Whetstone', index: '4002' },
        { name: 'Wyverns Wing Leather', index: '4003' },
        { name: 'Shadow Blade Fragment', index: '4004' },
        { name: 'Spectors Hand', index: '4005' },
        { name: 'Amplifying Grimoire', index: '4006' },
        { name: 'Ferocious Flames', index: '4007' },
        { name: 'Frigid Crystals', index: '4008' },
        { name: 'Punishers Lightning Shards', index: '4009' },
        { name: 'Chalice Of Silence', index: '4010' },
        { name: 'Lucky Bracer', index: '4011' },
        { name: 'Dragons Fang', index: '4012' },
        { name: 'Serene Ointment', index: '4013' },
        { name: 'Plague Brazier', index: '4014' },
        { name: 'Hunters Feather', index: '4015' },
        { name: 'Forlorn Hopes Pendant', index: '4016' },
        { name: 'Essence Bead', index: '4017' },
        { name: 'Sages Book', index: '4018' },
        { name: 'Mirror Of Soul Liberation', index: '4019' },
        { name: 'Pledge Of Strength', index: '4020' },
        { name: 'Pledge Of Agility', index: '4021' },
        { name: 'Pledge Of Intelligence', index: '4022' },
        { name: 'Fruit Of Growth', index: '4023' },
        { name: 'Mages Cloak', index: '4024' },
        { name: 'Babarians Prosthetic Hand', index: '4025' },
        { name: 'Crescent Sickle', index: '4026' },
        { name: 'Crimson Cactus', index: '4027' },
        { name: 'Steel Sawblade', index: '4028' },
        { name: 'Scorpions Tail Venom', index: '4029' },
        { name: 'Silent Furnace', index: '4030' },
        { name: 'Goose Statue', index: '4031' },
        { name: 'Thiefs Will', index: '4032' },
        { name: 'Mark Of Caravan', index: '4033' },
        { name: 'Catlike Stride', index: '4034' },
        { name: 'Blessed Power', index: '4035' },
        { name: 'Soul Staff', index: '4036' },
        { name: 'Reconciliation', index: '4037' },
        { name: 'Great Sages Journal', index: '4038' },
        { name: 'Hunters Thumbring', index: '4039' },
        { name: 'Grave Robbers Boots', index: '4040' },
        { name: 'Evasion Hood', index: '4041' },
        { name: 'Prayer Of Moderation', index: '4042' },
        { name: 'Holy Powder', index: '4043' },
        { name: 'Mark Of Regret', index: '4044' },
        { name: 'Eternal Ember', index: '4045' },
        { name: 'Tear Of The Goddess', index: '4046' },
        { name: 'Chilling Arrowhead', index: '4047' },
        { name: 'Frozen Gothic', index: '4048' },
        { name: 'Mysterious Coins', index: '4049' },
        { name: 'Melting Heart', index: '4050' },
        { name: 'Insignia Of Despair', index: '4051' },
        { name: 'Ignited Flowers', index: '4052' },
        { name: 'Heated Stone', index: '4053' },
        { name: 'Frozen Rose', index: '4054' },
        { name: 'Magical Powder Keg', index: '4055' },
        { name: 'Azure Flame Candle', index: '4056' },
        { name: 'Languishing Death', index: '4057' },
        { name: 'Blizzard Collectors Orb', index: '4058' },
        { name: 'Dragons Elixir', index: '4059' },
        { name: 'Ice Dragons Scales', index: '4060' },
        { name: 'Statue Of Wrath', index: '4061' },
        { name: 'Mark Of Judgment', index: '4062' },
        { name: 'Lightning Hook Chain', index: '4063' },
        { name: 'Silver Cross', index: '4064' },
        { name: 'Pandemic Joy', index: '4065' },
        { name: 'Snakehead Ornament', index: '4066' },
        { name: 'Diseased Herb', index: '4067' },
        { name: 'Oath Of Pride', index: '4068' },
        { name: 'Warriors Horn', index: '4069' },
        { name: 'Dragons Condensed Blood', index: '4070' },
        { name: 'Doctrine Of Freedom', index: '4071' },
        { name: 'Sutra Of Liberation', index: '4072' },
        { name: 'Soul Waterskin', index: '4073' },
        { name: 'Censer Of Strength', index: '4074' },
        { name: 'Censer Of Agility', index: '4075' },
        { name: 'Censer Of Intelligence', index: '4076' },
        { name: 'Insignia Of Blessing', index: '4077' },
        { name: 'Rosary Of Blessing', index: '4078' },
        { name: 'Quiver Of Blessing', index: '4079' },
        { name: 'Frozen Moss', index: '4080' },
        { name: 'Holy Lightning Rod', index: '4081' },
        { name: 'Broken Skull', index: '4082' },
        { name: 'Eyes Of Greed', index: '4083' },
        { name: 'Endless Glass', index: '4084' },
        { name: 'Golden Tooth', index: '4085' },
        { name: 'Cloak Of Wolf', index: '4086' },
        { name: 'Broken Shackles', index: '4087' },
        { name: 'Blood Stained Wolf Leather', index: '4088' },
        { name: 'Pot Of Greed', index: '4089' },
        { name: 'Bonethooth Ornament', index: '4090' },
        { name: 'Warriors Drum', index: '4091' },
        { name: 'Corroded Axe Blade', index: '4092' },
        { name: 'Merciless Destroyer', index: '4093' },
        { name: 'Northern Red Herb', index: '4094' },
        { name: 'Concealed Blade', index: '4095' },
        { name: 'Baby Leech', index: '4096' },
        { name: 'Blood Diamond', index: '4097' },
        { name: 'Bat Statue', index: '4098' },
        { name: 'Cursed Eating Key', index: '4099' },
        { name: 'Dwarfs Versatile Key', index: '4100' },
        { name: 'Relic Detector', index: '4101' },
        { name: 'Contracts In Caravan', index: '4102' },
        { name: 'Legendary Crusher', index: '4103' },
        { name: 'Heated Anvil', index: '4104' },
        { name: 'Craftsmans Grindstone', index: '4105' },
        { name: 'White Mask', index: '4106' },
        { name: 'Pieces Of Faith', index: '4107' },
        { name: 'Pieces Of Freedom', index: '4108' },
        { name: 'Unity', index: '4109' },
        { name: 'Hawk Sculpture', index: '4110' },
        { name: 'Small Sword', index: '4111' },
        { name: 'Dueling Shoes', index: '4112' },
        { name: 'Training Manual', index: '4113' },
        { name: 'Wizards Shoes', index: '4114' },
        { name: 'Mythril Armor', index: '4115' },
        { name: 'Principles Of Rune', index: '4116' },
        { name: 'Heart Of Frost Golem', index: '4117' },
        { name: 'Blessing Of The Moon', index: '4118' },
        { name: 'Moons Revenge', index: '4119' },
        { name: 'Protection Of Archmage', index: '4120' },
        { name: 'Sealed Devil Chest', index: '4121' },
        { name: 'Willpower Of Forlorn Hope', index: '4122' },
        { name: 'Drakans Hunter Knife', index: '4123' },
        { name: 'The Last Of Soul Liberators', index: '4124' },
        { name: 'Spiritual Guide', index: '4125' },
        { name: 'Asceticism Of Eternity', index: '4126' },
        { name: 'Transcendental Flute', index: '4127' },
        { name: 'Blessing Of Valor', index: '4128' },
        { name: 'Blessing Of The Sniper', index: '4129' },
        { name: 'Blessing Of Wisdom', index: '4130' },
        { name: 'Blessing Of Diligence', index: '4131' },
        { name: 'Pendant Of Desire', index: '4132' },
        { name: 'The Ivy Of Greed', index: '4133' },
        { name: 'Root Of Avarice', index: '4134' },
        { name: 'Wolfs Torn Jaw', index: '4135' },
        { name: 'Scorched Claw', index: '4136' },
        { name: 'Fragment Of Resentment', index: '4137' },
        { name: 'Entwined Hatred', index: '4138' },
        { name: 'Abandoned Wooden Shield', index: '4139' },
        { name: 'Blue Clover', index: '4140' },
        { name: 'Test Of Faith', index: '4141' },
        { name: 'Rainbow Pendant', index: '4142' },
        { name: 'Cains Pendulum', index: '4143' },
        { name: 'Mark Of Great Merchant', index: '4144' },
        { name: 'Golden Camel Statue', index: '4145' },
        { name: 'Art Of Negotiation', index: '4146' },
        { name: 'Great Merchants Charm', index: '4147' },
        { name: 'Stem Of Recovery', index: '4148' },
        { name: 'Soul Reaping Scythe', index: '4149' },
        { name: 'Pendant Of Balance', index: '4150' },
        { name: 'Reaper Statue', index: '4151' },
        { name: 'Drink Of Awakening', index: '4152' },
        { name: 'Swift Kukri', index: '4153' },
        { name: 'Soul Ring', index: '4154' },
        { name: 'Sedative', index: '4155' },
        { name: 'Interpretation Of Magic', index: '4156' },
        { name: 'Origin Of Plague', index: '4157' },
        { name: 'Frozen Shackles', index: '4158' },
        { name: 'Trolls Blood', index: '4159' },
        { name: 'Sanctuary Of The Soul', index: '4160' },
        { name: 'Celestial Talent', index: '4161' },
        { name: 'Predators Bone', index: '4162' },
        { name: 'Predators Spinal Cord', index: '4163' },
        { name: 'Seal Of The Black Wolf', index: '4164' },
        { name: 'Wolfs Head Ornament', index: '4165' },
        { name: 'Shadow Eating Relics', index: '4166' },
        { name: 'Giant Sack Of Money', index: '4167' },
        { name: 'Blessed Relic Box', index: '4168' },
        { name: 'Black Wolf Armor', index: '4169' },
        { name: 'Broken Holy Lance', index: '4170' },
        { name: 'Archmages Hat', index: '4171' },
        { name: 'Warriors Prayer', index: '4172' },
        { name: 'Gauntlets Of Soul Harvest', index: '4173' },
        { name: 'Inevitable Death', index: '4174' },
        { name: 'Blood Eating Flower', index: '4175' },
        { name: 'Endless Willpower', index: '4176' },
        { name: 'Executioners Beheading Blade', index: '4177' },
        { name: 'Magic Explorer', index: '4178' },
        { name: 'Archmages Watch', index: '4179' },
        { name: 'Anguish', index: '4180' },
        { name: 'Contractor Hourglass', index: '4181' },
        { name: 'Dragon Coin', index: '4182' },
        { name: 'Another Opportunity', index: '4183' },
        { name: 'Chaos Orb', index: '4184' },
        { name: 'Life Blood Pouch', index: '4185' },
        { name: 'Bell Of Silence', index: '4186' },
        { name: 'Mysterious Cube', index: '4187' },
        { name: 'Petrified Ancient Dragon Eyeball', index: '4188' },
        { name: 'Sealed Chest', index: '4189' },
        { name: 'Prisoner Iron Helmet', index: '4190' },
        { name: 'The Four Pledges', index: '4191' },
        { name: 'Sage Severed Ear', index: '4192' },
        { name: 'Devil Dice', index: '4193' }            
    ];

    return (
        <div className="relic-list">
            {relicList.map((relic, index) => (
                <Relic key={index} name={relic.name} />
            ))}
        </div>
    )
}

export default RelicList;